# serverless.yml

service: my-express-application

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  tableName: "users-table-${self:provider.stage}"
  dynamodb:
    stages:
      - dev
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - cognito-idp:AdminGetUser
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn"] }
        - arn:aws:cognito-idp:us-west-2:544012685056:userpool/us-west-2_SXVQTWO6o
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: index.handler
    events:
      - http: 
          path: /
          method: ANY
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:544012685056:userpool/us-west-2_SXVQTWO6o
            claims:
              - email
  getUser:
    handler: index.handler
    events:
      - http: "GET /users/{proxy+}"
  createUser:
    handler: index.handler
    events:
      - http: "POST /users"

resources:
  Resources:
    UsersDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:provider.stage}-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:provider.stage}-user-pool-client
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: false
